#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
source tests/test-helpers.sh

echo "test: Hyprland Lua config generation (split modules)"
tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

info() { :; }
fatal() {
  printf 'fatal: %s\n' "$*" >&2
  return 1
}
in_target() { :; }

source scripts/60-hyprland.sh

TARGET="${tmp}/target"
TARGET_USERNAME="tester"
HYPR_AUTOLOGIN=1

# The user config is upstream's example/hyprland.lua from the staged
# Hyprland source tree, SPLIT into one module per upstream section header
# and loaded by a small entry file via require(). Stage a representative
# fake example: preamble, two sections, and a cross-section local.
mkdir -p "${TARGET}${HYPR_SRC_DIR}/hyprland/example"
cat >"${TARGET}${HYPR_SRC_DIR}/hyprland/example/hyprland.lua" <<'EOF'
-- This is an example Hyprland Lua config file (fake for tests).
-- Refer to the wiki for more information.

---------------------
---- MY PROGRAMS ----
---------------------
local terminal = "kitty"
local mainMod = "SUPER"

------------------
---- KEYBINDS ----
------------------
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
EOF

configure_session

hypr_dir="${TARGET}/home/${TARGET_USERNAME}/.config/hypr"
entry="${hypr_dir}/hyprland.lua"
legacy_config="${hypr_dir}/hyprland.conf"

if [[ -f "${entry}" ]]; then
  echo "  ok: entry hyprland.lua exists"
  cfg="$(<"${entry}")"
  assert_contains "${cfg}" "fake for tests" \
    "upstream preamble preserved in the entry file"
  assert_contains "${cfg}" 'require("my-programs")' \
    "entry requires the programs module"
  assert_contains "${cfg}" 'require("keybinds")' \
    "entry requires the keybinds module"
  assert_contains "${cfg}" 'require("hypr-deb")' \
    "entry requires the installer additions module"
  # Load order: upstream sections in original order, hypr-deb last.
  progs_line="$(printf '%s\n' "${cfg}" | grep -n 'require("my-programs")' | cut -d: -f1 | head -n1 || true)"
  binds_line="$(printf '%s\n' "${cfg}" | grep -n 'require("keybinds")' | cut -d: -f1 | head -n1 || true)"
  deb_line="$(printf '%s\n' "${cfg}" | grep -n 'require("hypr-deb")' | cut -d: -f1 | head -n1 || true)"
  if [[ -n "${progs_line}" && -n "${binds_line}" && -n "${deb_line}" ]] &&
    ((progs_line < binds_line && binds_line < deb_line)); then
    echo "  ok: modules load in upstream order, installer additions last"
  else
    echo "  FAIL: require order wrong (programs=${progs_line} keybinds=${binds_line} hypr-deb=${deb_line})" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  fi
  if [[ "${cfg}" == *"autogenerated = true"* ]]; then
    echo "  FAIL: full upstream config must not set the autogenerated flag" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  else
    echo "  ok: no autogenerated warning bar with the full config"
  fi
else
  echo "  FAIL: entry hyprland.lua does not exist" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

# Section modules: content verbatim except top-level locals become globals
# (locals are chunk-scoped; require()'d files are separate chunks, so
# cross-file variables like mainMod must be global to keep resolving).
if [[ -f "${hypr_dir}/my-programs.lua" ]]; then
  progs="$(<"${hypr_dir}/my-programs.lua")"
  assert_contains "${progs}" 'terminal = "kitty"' \
    "programs module keeps the declaration"
  if printf '%s\n' "${progs}" | grep -q '^local '; then
    echo "  FAIL: top-level locals must become globals in split modules" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  else
    echo "  ok: top-level locals stripped to globals"
  fi
else
  echo "  FAIL: my-programs.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

if [[ -f "${hypr_dir}/keybinds.lua" ]]; then
  binds="$(<"${hypr_dir}/keybinds.lua")"
  assert_contains "${binds}" \
    'hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))' \
    "keybinds content survives verbatim"
else
  echo "  FAIL: keybinds.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

# Installer additions: separate module, acknowledgment-gated welcome (the
# marker lands only when the app exits cleanly — app first, && touch after).
if [[ -f "${hypr_dir}/hypr-deb.lua" ]]; then
  deb="$(<"${hypr_dir}/hypr-deb.lua")"
  assert_contains "${deb}" "/usr/local/bin/hyprland-welcome" \
    "welcome app launched by absolute path"
  # shellcheck disable=SC2016  # literal needle; $marker expands at login
  assert_contains "${deb}" \
    '/usr/local/bin/hyprland-welcome && touch "$marker"' \
    "marker touched only after the app is acknowledged"
  # The exec must run on the hyprland.start event — a bare top-level
  # hl.exec_cmd fires at config-parse time, before the compositor is up,
  # so the GUI client has no Wayland display and never launches.
  assert_contains "${deb}" 'hl.on("hyprland.start"' \
    "welcome exec registered on the hyprland.start autostart event"
  assert_contains "${deb}" "uwsm finalize" \
    "compositor finalizes the UWSM session on start"
else
  echo "  FAIL: hypr-deb.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

if [[ -e "${legacy_config}" ]]; then
  echo "  FAIL: legacy hyprland.conf must not be generated" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
else
  echo "  ok: legacy hyprland.conf is not generated"
fi

# Quiet VT handoff (issue #12): the session must launch through the
# journal-routing wrapper so uwsm/Hyprland chatter never paints VT1.
wrapper="${TARGET}/usr/local/bin/hypr-session"
if [[ -x "${wrapper}" ]]; then
  echo "  ok: hypr-session wrapper staged executable"
  assert_contains "$(<"${wrapper}")" "systemd-cat" \
    "wrapper routes session output to the journal"
  assert_contains "$(<"${wrapper}")" "UWSM_SILENT_START=2" \
    "wrapper suppresses uwsm startup chatter"
else
  echo "  FAIL: hypr-session wrapper missing or not executable" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi
greetd_cfg="$(<"${TARGET}/etc/greetd/config.toml")"
assert_contains "${greetd_cfg}" '/usr/local/bin/hypr-session' \
  "greetd session command uses the wrapper"

# Greeter branch (no autologin): tuigreet builds its session menu from
# ${XDG_DATA_DIRS}/wayland-sessions, where the uwsm/Hyprland source builds
# drop hyprland*.desktop entries that bypass the silencing wrapper and
# reintroduce VT chatter (issue #12). --sessions must aim at our own dir
# (replaces the scan, no fallback) holding exactly one curated entry that
# launches the silent wrapper, and --cmd must be omitted so tuigreet
# defaults to that lone "Hyprland" session.
greeter_target="${tmp}/greeter-target"
mkdir -p "${greeter_target}${HYPR_SRC_DIR}/hyprland/example"
cp "${TARGET}${HYPR_SRC_DIR}/hyprland/example/hyprland.lua" \
  "${greeter_target}${HYPR_SRC_DIR}/hyprland/example/hyprland.lua"
(
  # Stub the chroot helper so `command -v tuigreet` resolves to a path;
  # stay quiet for the unrelated chown/systemctl block.
  in_target() { [[ "$*" == *"command -v tuigreet"* ]] && echo /usr/bin/tuigreet || :; }
  TARGET="${greeter_target}"
  HYPR_AUTOLOGIN=0
  configure_session
)
greeter_cfg="$(<"${greeter_target}/etc/greetd/config.toml")"
assert_contains "${greeter_cfg}" 'tuigreet' \
  "greeter branch uses tuigreet"
assert_contains "${greeter_cfg}" '--sessions /etc/greetd/sessions' \
  "tuigreet --sessions points at our curated dir (no bypass menu)"
# tuigreet's power menu must use absolute-path commands: its built-in
# defaults exec the bare `shutdown` binary (prefixed with a bare `setsid`)
# via a PATH lookup the greeter cannot satisfy, so both actions fail with
# "file not found" (issue #49). --power-no-setsid + absolute systemctl
# paths make tuigreet exec the binary directly, independent of PATH.
assert_contains "${greeter_cfg}" '--power-no-setsid' \
  "tuigreet skips the bare setsid prefix (unresolvable without PATH)"
assert_contains "${greeter_cfg}" "--power-shutdown '/usr/bin/systemctl poweroff'" \
  "tuigreet shut down uses an absolute-path command (issue #49)"
assert_contains "${greeter_cfg}" "--power-reboot '/usr/bin/systemctl reboot'" \
  "tuigreet reboot uses an absolute-path command (issue #49)"
if [[ "${greeter_cfg}" == *"--cmd"* ]]; then
  echo "  FAIL: greeter must omit --cmd so the curated session is the default" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
else
  echo "  ok: greeter omits --cmd (lone session becomes the default)"
fi
greeter_entry="${greeter_target}/etc/greetd/sessions/hyprland.desktop"
if [[ -f "${greeter_entry}" ]]; then
  echo "  ok: curated greeter session entry staged"
  entry_txt="$(<"${greeter_entry}")"
  assert_contains "${entry_txt}" 'Name=Hyprland' \
    "curated session is named Hyprland"
  assert_contains "${entry_txt}" 'Exec=/usr/local/bin/hypr-session' \
    "curated session launches the silent wrapper"
  # The bypassing upstream names must NOT be reintroduced here.
  if [[ "${entry_txt}" == *"uwsm start"* ]]; then
    echo "  FAIL: curated entry must go through the wrapper, not raw uwsm start" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  fi
else
  echo "  FAIL: ${greeter_entry} (curated single session) missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

# xdg-desktop-portal-hyprland installs to /usr/local/libexec (issue #58); the
# build-dep purge must scan that path too, or xdph's libsdbus-c++2 runtime —
# pulled in only by the purged -dev package — gets autoremoved and the portal
# binary breaks. Pin it by including libexec binaries in the ldd survival scan.
assert_contains "$(declare -f purge_build_deps)" '/usr/local/libexec' \
  "purge scans /usr/local/libexec so xdph runtime libs survive (issue #58)"

# A missing staged example is a loud failure, not a silent fallback.
# fatal exits in the real installer (lib/01-log.sh); mirror that here.
assert_fails "missing staged example config is fatal" bash -c "
  info() { :; }
  fatal() { exit 1; }
  in_target() { :; }
  source scripts/60-hyprland.sh
  TARGET='${tmp}/empty-target'
  TARGET_USERNAME='tester'
  HYPR_AUTOLOGIN=1
  configure_session
"

# An example without recognizable section headers means upstream changed
# the format — fail loudly rather than producing an empty config.
mkdir -p "${tmp}/flat-target${HYPR_SRC_DIR}/hyprland/example"
printf -- '-- no sections here\nhl.bind("SUPER + Q", hl.dsp.exit())\n' \
  >"${tmp}/flat-target${HYPR_SRC_DIR}/hyprland/example/hyprland.lua"
assert_fails "headerless upstream example is fatal" bash -c "
  info() { :; }
  fatal() { exit 1; }
  in_target() { :; }
  source scripts/60-hyprland.sh
  TARGET='${tmp}/flat-target'
  TARGET_USERNAME='tester'
  HYPR_AUTOLOGIN=1
  configure_session
"

ver_body="$(bash -c 'source lib/00-config.sh; source lib/01-log.sh
  source scripts/90-verify.sh
  declare -f phase_verify' 2>/dev/null || true)"
assert_contains "${ver_body}" "welcome app installed" \
  "verify checks the welcome binary exists"

finish_test
