#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
source tests/test-helpers.sh

echo "test: Hyprland Lua config generation (split modules)"
tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

info() { :; }
fatal() {
  printf 'fatal: %s\n' "$*" >&2
  return 1
}
in_target() { :; }

source scripts/60-hyprland.sh

TARGET="${tmp}/target"
TARGET_USERNAME="tester"
HYPR_AUTOLOGIN=1

# The user config is upstream's example/hyprland.lua from the staged
# Hyprland source tree, SPLIT into one module per upstream section header
# and loaded by a small entry file via require(). Stage a representative
# fake example: preamble, two sections, and a cross-section local.
mkdir -p "${TARGET}${HYPR_SRC_DIR}/hyprland/example"
cat >"${TARGET}${HYPR_SRC_DIR}/hyprland/example/hyprland.lua" <<'EOF'
-- This is an example Hyprland Lua config file (fake for tests).
-- Refer to the wiki for more information.

---------------------
---- MY PROGRAMS ----
---------------------
local terminal = "kitty"
local mainMod = "SUPER"

------------------
---- KEYBINDS ----
------------------
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
EOF

configure_session

hypr_dir="${TARGET}/home/${TARGET_USERNAME}/.config/hypr"
entry="${hypr_dir}/hyprland.lua"
legacy_config="${hypr_dir}/hyprland.conf"

if [[ -f "${entry}" ]]; then
  echo "  ok: entry hyprland.lua exists"
  cfg="$(<"${entry}")"
  assert_contains "${cfg}" "fake for tests" \
    "upstream preamble preserved in the entry file"
  assert_contains "${cfg}" 'require("my-programs")' \
    "entry requires the programs module"
  assert_contains "${cfg}" 'require("keybinds")' \
    "entry requires the keybinds module"
  assert_contains "${cfg}" 'require("hypr-deb")' \
    "entry requires the installer additions module"
  # Load order: upstream sections in original order, hypr-deb last.
  progs_line="$(printf '%s\n' "${cfg}" | grep -n 'require("my-programs")' | cut -d: -f1 | head -n1 || true)"
  binds_line="$(printf '%s\n' "${cfg}" | grep -n 'require("keybinds")' | cut -d: -f1 | head -n1 || true)"
  deb_line="$(printf '%s\n' "${cfg}" | grep -n 'require("hypr-deb")' | cut -d: -f1 | head -n1 || true)"
  if [[ -n "${progs_line}" && -n "${binds_line}" && -n "${deb_line}" ]] &&
    ((progs_line < binds_line && binds_line < deb_line)); then
    echo "  ok: modules load in upstream order, installer additions last"
  else
    echo "  FAIL: require order wrong (programs=${progs_line} keybinds=${binds_line} hypr-deb=${deb_line})" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  fi
  if [[ "${cfg}" == *"autogenerated = true"* ]]; then
    echo "  FAIL: full upstream config must not set the autogenerated flag" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  else
    echo "  ok: no autogenerated warning bar with the full config"
  fi
else
  echo "  FAIL: entry hyprland.lua does not exist" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

# Section modules: content verbatim except top-level locals become globals
# (locals are chunk-scoped; require()'d files are separate chunks, so
# cross-file variables like mainMod must be global to keep resolving).
if [[ -f "${hypr_dir}/my-programs.lua" ]]; then
  progs="$(<"${hypr_dir}/my-programs.lua")"
  assert_contains "${progs}" 'terminal = "kitty"' \
    "programs module keeps the declaration"
  if printf '%s\n' "${progs}" | grep -q '^local '; then
    echo "  FAIL: top-level locals must become globals in split modules" >&2
    TEST_FAILURES=$((TEST_FAILURES + 1))
  else
    echo "  ok: top-level locals stripped to globals"
  fi
else
  echo "  FAIL: my-programs.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

if [[ -f "${hypr_dir}/keybinds.lua" ]]; then
  binds="$(<"${hypr_dir}/keybinds.lua")"
  assert_contains "${binds}" \
    'hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))' \
    "keybinds content survives verbatim"
else
  echo "  FAIL: keybinds.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

# Installer additions: separate module, acknowledgment-gated welcome (the
# marker lands only when the app exits cleanly — app first, && touch after).
if [[ -f "${hypr_dir}/hypr-deb.lua" ]]; then
  deb="$(<"${hypr_dir}/hypr-deb.lua")"
  assert_contains "${deb}" "/usr/local/bin/hyprland-welcome" \
    "welcome app launched by absolute path"
  # shellcheck disable=SC2016  # literal needle; $marker expands at login
  assert_contains "${deb}" \
    '/usr/local/bin/hyprland-welcome && touch "$marker"' \
    "marker touched only after the app is acknowledged"
else
  echo "  FAIL: hypr-deb.lua module missing" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

if [[ -e "${legacy_config}" ]]; then
  echo "  FAIL: legacy hyprland.conf must not be generated" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
else
  echo "  ok: legacy hyprland.conf is not generated"
fi

# A missing staged example is a loud failure, not a silent fallback.
# fatal exits in the real installer (lib/01-log.sh); mirror that here.
assert_fails "missing staged example config is fatal" bash -c "
  info() { :; }
  fatal() { exit 1; }
  in_target() { :; }
  source scripts/60-hyprland.sh
  TARGET='${tmp}/empty-target'
  TARGET_USERNAME='tester'
  HYPR_AUTOLOGIN=1
  configure_session
"

# An example without recognizable section headers means upstream changed
# the format — fail loudly rather than producing an empty config.
mkdir -p "${tmp}/flat-target${HYPR_SRC_DIR}/hyprland/example"
printf -- '-- no sections here\nhl.bind("SUPER + Q", hl.dsp.exit())\n' \
  >"${tmp}/flat-target${HYPR_SRC_DIR}/hyprland/example/hyprland.lua"
assert_fails "headerless upstream example is fatal" bash -c "
  info() { :; }
  fatal() { exit 1; }
  in_target() { :; }
  source scripts/60-hyprland.sh
  TARGET='${tmp}/flat-target'
  TARGET_USERNAME='tester'
  HYPR_AUTOLOGIN=1
  configure_session
"

ver_body="$(bash -c 'source lib/00-config.sh; source lib/01-log.sh
  source scripts/90-verify.sh
  declare -f phase_verify' 2>/dev/null || true)"
assert_contains "${ver_body}" "welcome app installed" \
  "verify checks the welcome binary exists"

finish_test
