#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
source tests/test-helpers.sh

echo "test: Hyprland Lua config generation"
tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

info() { :; }
fatal() {
  printf 'fatal: %s\n' "$*" >&2
  return 1
}
in_target() { :; }

source scripts/60-hyprland.sh

TARGET="${tmp}/target"
TARGET_USERNAME="tester"
HYPR_AUTOLOGIN=1

configure_session

lua_config="${TARGET}/home/${TARGET_USERNAME}/.config/hypr/hyprland.lua"
legacy_config="${TARGET}/home/${TARGET_USERNAME}/.config/hypr/hyprland.conf"

if [[ -f "${lua_config}" ]]; then
  echo "  ok: user hyprland.lua exists"
  config="$(<"${lua_config}")"
  assert_contains "${config}" "hl.config({ autogenerated = true })" \
    "Lua config carries the autogenerated marker"
  assert_contains "${config}" "hl.monitor({" \
    "Lua config defines the fallback monitor"
  assert_contains "${config}" \
    'hl.bind(main_mod .. " + Return", hl.dsp.exec_cmd("kitty"))' \
    "Lua config launches kitty"
  assert_contains "${config}" \
    'hl.bind(main_mod .. " + Q", hl.dsp.window.close())' \
    "Lua config closes the active window"
  assert_contains "${config}" \
    'hl.bind(main_mod .. " + SHIFT + E", hl.dsp.exit())' \
    "Lua config exits Hyprland"
  assert_contains "${config}" "hyprland-welcome" \
    "Lua config launches the welcome app"
  assert_contains "${config}" ".welcome-shown" \
    "welcome launch is gated by the first-login marker"
  assert_contains "${config}" "/usr/local/bin/hyprland-welcome" \
    "welcome app referenced by absolute path"
else
  echo "  FAIL: user hyprland.lua does not exist" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
fi

if [[ -e "${legacy_config}" ]]; then
  echo "  FAIL: legacy hyprland.conf must not be generated" >&2
  TEST_FAILURES=$((TEST_FAILURES + 1))
else
  echo "  ok: legacy hyprland.conf is not generated"
fi

finish_test
